-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################

-- AUTOGENERATED HYPRLAND CONFIG.

-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

-- autogenerated = 1 # remove this line to remove the warning

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hypr.land/Configuring/Monitors/

-- monitor=,preferred,auto,auto

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = 1,
})

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use

local terminal = "kitty"

local fileManager = "dolphin"

local menu = "wofi --show drun"

local browser = "chromium"

local browser_video = "chromium --disable-gpu --user-data-dir=$(mktemp -d) --enable-features=WebUIDarkMode --force-dark-mode"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal



--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("QT_QPA_PLATFORM", "wayland")

hl.env("QT_QPA_PLATFORMTHEME", "kde")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "x11")

-- env = LIBVA_DRIVER_NAME,nvidia

-- env = XDG_SESSION_TYPE,wayland

-- env = GBM_BACKEND,nvidia-drm

-- env = __GLX_VENDOR_LIBRARY_NAME,nvidia

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hypr.land/Configuring/Permissions/

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

hl.config({
    ecosystem = {
        --   enforce_permissions = 1
        no_update_news = true,
        no_donation_nag = true,
    },
})

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow

-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 8,
        border_size = 2,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 10,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

-- hl.config({
--    animations = {
--        enabled = true,
--		speed = 4.0,
--        -- Default animations, see https://wiki.hypr.land/Configuring/Animations/ for more
--    },
-- })

hl.curve( "overshoot", { type = "bezier", points = { {0.5, 0.9}, {0.1, 1.1} } } )
hl.curve( "rubber", { type = "spring", mass = 1, stiffness = 1000, dampening = 70 } )
hl.curve( "workspace_rubber", { type = "spring", mass = 1, stiffness = 1000, dampening = 70 } )



hl.animation({
    leaf = "windows",
	spring = "rubber",
	curve = "default",
    enabled = true,
    speed = 2,
    curve = "default",
})

hl.animation({
    leaf = "workspaces",
	spring = "workspace_rubber",
	curve = "default",
    enabled = true,
    speed = 0.2,
    curve = "default",
})

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]

-- windowrule = rounding 0, floating:0, onworkspace:w[tv1]

-- windowrule = bordersize 0, floating:0, onworkspace:f[1]

-- windowrule = rounding 0, floating:0, onworkspace:f[1]

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        --    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        force_split = 2,
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})


hl.config({
    misc = {
        focus_on_activate = false,
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = 0,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true,
        -- If true disables the random hyprland logo / anime girl background. :(
		disable_splash_rendering = true,
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "caps:escape",
        kb_rules = "",
        emulate_discrete_scroll = 0,
        follow_mouse = 2,
        sensitivity = -0.2,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#gestures

-- gestures {

--    workspace_swipe = false

-- }

-- Example per-device config

-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "mx-anywhere-2s-mouse",
    sensitivity = -0.95,
})

--##################

--##    CURSOR   ###

--##################

hl.config({
    cursor = {
        hide_on_key_press = true,
        inactive_timeout = 10,
    },
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("kitty -e tmux a"))

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("[float] wl-paste | feh -"))

hl.bind(mainMod .. " + " .. "N", hl.dsp.exec_cmd("chromium --disable-gpu --user-data-dir=$(mktemp -d) --enable-features=WebUIDarkMode --force-dark-mode"))
-- bind = $mainMod, M, exit,

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("dolphin"))

hl.bind(mainMod .. " + " .. "B", hl.dsp.exec_cmd("chromium"))

-- bind = $mainMod, V, togglefloating,

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("wofi --show drun"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

-- bind = $mainMod, J, togglesplit, # dwindle

hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "left" }))

-- dwindle

-- bind = $mainMod, K, movefocus, l

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. "S", hl.dsp.exec_cmd("hyprshot -m window -m active"))

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("/home/david/.config/hypr/touchpad.sh"))

hl.bind(mainMod .. " + " .. "Y", hl.dsp.exec_cmd("kitty -e yazi"))

hl.bind(mainMod .. " + " .. "U", hl.dsp.exec_cmd("[workspace special silent] kitty -e udiskie-umount -a"))

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("[workspace special silent] kitty -e udiskie-mount -a"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("fish -c power-off"))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "H", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "CONTROL" .. " + " .. "H", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more

-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule

-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- Ignore maximize requests from apps. You'll probably like this.

-- hl.window_rule({
--    name  = "suppress_event_maxim",
--    match = {
--        match = "class .*",
--    },
--    -- TODO: review rule: "suppress_event maximize"
-- })

-- misc { initial_workspace_tracking = 2 }

-- Fix some dragging issues with XWayland

-- windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

-- hl.window_rule({
--    name  = "no_initial_focus_1",
--    match = {
--        match = "pin 0",
--    },
--    -- TODO: review rule: "no_initial_focus 1"
--})

-- hl.window_rule({
--     name  = "match_class__browser",
--     match = {
--         class = "workspace 2 silent",
--     },
--     -- TODO: review rule: "match:class $browser"
-- })

-- hl.window_rule({
--     name  = "match_class___bambus",
--     match = {
--         class = "workspace 3 silent",
--     },
--     -- TODO: review rule: "match:class ^(BambuStudio)$"
-- })


hl.window_rule({
    name = "silent-bambu-launch",
    match = {
        class = "BambuStudio"
    },
    workspace = "3 silent", -- Opens the app on workspace 3 without switching focus
    no_initial_focus = true
})





hl.window_rule({
  name = "match_bambu_class",
  match = { 
    class = "BambuStudio" 
  },
  workspace = "3"
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprlock")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("mako")
    hl.exec_cmd("[workspace 1] kitty -e tmux")
    hl.exec_cmd("[workspace 2 silent] chromium")

    -- hl.exec_cmd("if [ $(date +%H) -lt 10 ]; then hyprctl dispatch exec [workspace 3 silent] bambustudio; fi")
	if tonumber(os.date("%H")) < 10 then
		hl.exec_cmd("touch ~/bambu-startup")
		hl.exec_cmd('echo $(date +%H) >> ~/bambu-startup')
		hl.exec_cmd("[workspace 3 silent] bambustudio")
	end

    hl.exec_cmd("[workspace 4 silent] slack")
    -- hl.exec_cmd("[workspace 3 silent] bambustudio")
end)







