set-option -g default-shell /usr/bin/fish

set-option -g message-style bg=blue

set -g mouse on
set -s escape-time 0

set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

bind C-p previous-window
bind C-n next-window
bind C-c new-window
bind -n M-q kill-window
bind -n M-x kill-pane
bind -n M-j select-pane -L
bind -n M-k select-pane -R
bind -n M-/ split-window -h
bind -n M-n new-window

bind -n M-0 select-window -t 0
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9


set -g history-limit 50000
set -g display-time 4000
set -g status-interval 5
set -g focus-events on


set -g status-style bg=#690096
set -g status-justify centre
set -g status-left-length 40
set -g status-left "#(whoami)@#H - [#S]"
set -g status-right "%a %d %b %I:%M %p "
